name: deploy
on:
  push:
    branches:
      - xin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3.0.0
        with:
          python-version: "3.10"

      - uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: which python

      - name: Install dependencies
        run: |
          pip install sphinxcontrib-websupport 
          pip install .[doc] --use-feature=in-tree-build
          sudo apt update
          sudo apt install -y graphviz
          conda install ipykernel
          python -m ipykernel install --user --name ai --display-name "ai"

      - name: Build the book
        run: |
          cd docs
          sphinx-build -D language=zh_CN -b html ./ _build/html/


      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
